CREATE OR REPLACE DATABASE DB_SPRINT1;
CREATE OR REPLACE SCHEMA DB_SPRINT1.SCH_SPRINT1;
CREATE OR REPLACE STAGE DB_SPRINT1.SCH_SPRINT1.stage_SPRINT1 
	DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE MY_AWS 
	URL = 's3://awscopilpre' 
	CREDENTIALS = ( AWS_KEY_ID = 'AKIA3FLD5DMGEC6X26FY' AWS_SECRET_KEY = '5x55p833oG0LotYVY3ESXy08OT+2XkBif+ZUCcMg' ) 
	DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE TABLE DB_SPRINT1.SCH_SPRINT1.veg_table ( plant_name VARCHAR , UOM VARCHAR , Low_End_of_Range NUMBER(38, 0) , High_End_of_Range NUMBER(38, 0) ); 

CREATE TEMP FILE FORMAT DB_SPRINT1.SCH_SPRINT1.temp_file_format
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO DB_SPRINT1.SCH_SPRINT1.veg_table 
FROM (SELECT $1, $2, $3, $4
	FROM '@DB_SPRINT1.SCH_SPRINT1.MY_AWS') 
FILES = ('veg_plant_height.csv') 
FILE_FORMAT = 'DB_SPRINT1.SCH_SPRINT1.temp_file_format' 
ON_ERROR=ABORT_STATEMENT 
