CREATE OR REPLACE DATABASE DB_SPRINT1;
CREATE OR REPLACE SCHEMA DB_SPRINT1.SCH_SPRINT1;
CREATE OR REPLACE STAGE DB_SPRINT1.SCH_SPRINT1.stage_SPRINT1 
	DIRECTORY = ( ENABLE = true );

CREATE OR REPLACE STAGE MY_AWS 
	URL = 's3://awscopilpre' 
	CREDENTIALS = ( AWS_KEY_ID = $AWS_ACCESS_KEY_ID AWS_SECRET_KEY = $AWS_SECRET_ACCESS_KEY ) 
	DIRECTORY = ( ENABLE = true );


