CREATE OR REPLACE DATABASE DB_SPRINT1;
CREATE OR REPLACE SCHEMA DB_SPRINT1.SCH_SPRINT1;
CREATE OR REPLACE STAGE DB_SPRINT1.SCH_SPRINT1.stage_SPRINT1 
	DIRECTORY = ( ENABLE = true );
PUT file://C:/Users/pilpreco/Documents/Snowflake/Snowsqlgit/veg_plant_height.csv @DB_SPRINT1.SCH_SPRINT1.stage_SPRINT1 auto_compress=false;

CREATE TABLE DB_SPRINT1.SCH_SPRINT1.veg_plant_heigh_table ( plant_name VARCHAR , UOM VARCHAR , Low_End_of_Range NUMBER(38, 0) , High_End_of_Range NUMBER(38, 0) ); 

CREATE TEMP FILE FORMAT DB_SPRINT1.SCH_SPRINT1.temp_file_format
	TYPE=CSV
    SKIP_HEADER=1
    FIELD_DELIMITER=','
    TRIM_SPACE=TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY='"'
    REPLACE_INVALID_CHARACTERS=TRUE
    DATE_FORMAT=AUTO
    TIME_FORMAT=AUTO
    TIMESTAMP_FORMAT=AUTO; 

COPY INTO DB_SPRINT1.SCH_SPRINT1.veg_plant_heigh_table
FROM (SELECT $1, $2, $3, $4
	FROM '@DB_SPRINT1.SCH_SPRINT1.STAGE_SPRINT1') 
FILES = ('veg_plant_height.csv') 
FILE_FORMAT = 'DB_SPRINT1.SCH_SPRINT1.temp_file_format' 
ON_ERROR=ABORT_STATEMENT;